- name: 渲染哨兵实例配置文件
  template:
    src: sentinel.conf
    dest: '{{ install_dir }}/redis_{{ sentinel_port }}/conf/redis.conf'
    owner: redis
    group: redis
  register: configure_sentinel_result

- name: 渲染哨兵实例的 Systemd Service Unit 配置文件
  template:
    src: sentinel.service
    dest: '{% if ansible_distribution == "CentOS" %}/usr{% endif %}/lib/systemd/system/redis-{{ sentinel_port }}.service'

- name: 重启哨兵实例
  systemd:
    name: 'redis-{{ sentinel_port }}'
    daemon_reload: yes
    state: restarted
  when: configure_sentinel_result is changed