all:
  vars:
    # SSH 用户
    ansible_user: zze
    # SSH 密码
    ansible_ssh_pass: root1234
    # sudo 提权密码
    ansible_sudo_pass: root1234
    # Redis 编译好的二进制文件目录
    bin_dir: /opt/redis-bin
    # 安装目录
    install_dir: /opt/apps
    # Redis 实例端口
    instance_port: 6379
    # Redis 哨兵端口
    sentinel_port: 26379
    # Redis 密码
    password: c53b88722414ea2380531
  hosts:
    10.0.1.111:
      master: yes
    10.0.1.112:
    10.0.1.113:
